name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm i && npm run build
        working-directory: ./docs

      - name: Build and Deploy
        uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BUILD_DIR: docs/src/.vuepress/dist
          BUILD_SCRIPT: npm install && npm run-script build
