name: Deploy to Github Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm i && npm run build
        working-directory: ./docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/src/.vuepress/dist
